trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'install'
    arguments: 'install'
  displayName: 'npm install'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker-Hub-Connection' # Replace with the name of your Docker service connection
    repository: 'shivakrishna99/my-node-app' # Replace with the name of your Docker image
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      latest
  displayName: 'Build and push Docker image'
