trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker-Hub-Connection'
    repository: 'gitpractice/repositorys/date-fns'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
