# Node.js app build and Docker build/push
jobs:
- job: Build_and_Deploy
  displayName: Build and Deploy
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'npm run build'
      workingDir: '$(Build.SourcesDirectory)'
    displayName: 'npm run build'
  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      containerRegistry: 'Docker-Hub-Connection' # The name of your Docker service connection
      repository: 'shivakrishna99/my-node-app' # Replace "my-node-app" with the name of your Docker image
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        latest
