trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'npm install and build'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'node --version'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'Docker-Hub-Connection' # Replace with your Docker service connection name
    repository: 'shivakrishna99/my-node-app' # Replace with your Docker repository name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)'
    tags: |
      latest
