trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'run'
    arguments: 'build'
    workingDir: '$(Build.SourcesDirectory)'
  displayName: 'npm run build'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'Docker-Hub-Connection' # Replace with your Docker service connection name
    repository: 'shivakrishna99/my-node-app' # Replace with your Docker repository name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: 'latest'
